spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

    show-sql: true
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/sns
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
